# Generated by Django 5.2.7 on 2025-12-11 23:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_depart', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_actuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé'), ('VENDU', 'Vendu')], default='OUVERT', max_length=50)),
                ('gagnant_actuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_gagnes', to='enchere.utilisateur')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_vendus', to='enchere.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Enchere',
            fields=[
                ('id_enchere', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_enchere', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encheres', to='enchere.article')),
                ('encherisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encheres', to='enchere.utilisateur')),
            ],
            options={
                'indexes': [models.Index(fields=['article', '-date_enchere'], name='enchere_enc_article_95ca89_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['date_fin'], name='enchere_art_date_fi_71f557_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['vendeur'], name='enchere_art_vendeur_f79532_idx'),
        ),
    ]
